/**
 * Extension runtime configuration.
 *
 * This file is GENERATED by scripts/generate-extension-config.js before build.
 * It is gitignored to prevent credentials being committed.
 *
 * To set up: run `npm run build:extension` which calls the generate script first.
 * See scripts/generate-extension-config.js for details.
 */

export const SUPABASE_URL = '';
export const SUPABASE_ANON_KEY = '';
export const API_BASE = 'http://localhost:3000';
